In [1]:
import numpy as np
from jwst.residual_fringe.fourier import FourierSeries1D

In [2]:
frequencies = [0.25, 0.5]
mdl = FourierSeries1D(frequencies)
mdl.a0.value = 6
mdl.a1.value = 7
mdl.b0.value = 8
mdl.b1.value = 9

In [3]:
print(mdl)

Model: FourierSeries1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
     a0  b0  a1  b1
    --- --- --- ---
    6.0 8.0 7.0 9.0


In [4]:
print(mdl(1))

-2.999999999999999


In [5]:
6*np.sin(2*np.pi*0.25) + 8*np.cos(2*np.pi*0.25) + 7 * np.sin(2*np.pi*0.5) + 9 * np.cos(2*np.pi*0.5)

-2.9999999999999982

In [6]:
mdl.fit_deriv(2)

[1.2246467991473532e-16, -1.0, -2.4492935982947064e-16, 1.0]

In [7]:
[np.sin(2*np.pi*0.25*2), np.cos(2*np.pi*0.25*2), np.sin(2*np.pi*0.5*2), np.cos(2*np.pi*0.5*2)]

[1.2246467991473532e-16, -1.0, -2.4492935982947064e-16, 1.0]

In [8]:
from jwst.residual_fringe.fitter import ChiSqOutlierRejectionFitter
from astropy.modeling.fitting import LevMarLSQFitter

In [9]:
fitter = ChiSqOutlierRejectionFitter(LevMarLSQFitter())

In [10]:
x = np.linspace(0, 1, 3)
print(x)

[0.  0.5 1. ]


In [11]:
mdl.fit_deriv(x)

[array([0.        , 0.70710678, 1.        ]),
 array([1.00000000e+00, 7.07106781e-01, 6.12323400e-17]),
 array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])]

In [12]:
fitter._jacobian(mdl, x)

array([0.        , 0.70710678, 1.        ])